### ISSUE TITLE
No commands work.

### ISSUE THREAD

**Issue by NX721** [ArcerionDev/ProdigyMathGameBot#2]

**Comment by ArcerionDev** [comment]
yeah thanks but the bot is offline
![image](https://user-images.githubusercontent.com/60945964/109560406-d665f580-7aa9-11eb-9fff-69e7a8954710.png)

**Comment by ArcerionDev** [comment]
![image](https://user-images.githubusercontent.com/60945964/109560827-52603d80-7aaa-11eb-9c02-140eb703d7f7.png)
working fine for me

**Comment by NX721** [comment]
Really?

**Comment by NX721** [comment]
![image](https://user-images.githubusercontent.com/77288637/109565145-0adcb000-7ab0-11eb-963d-0618c4c72428.png)

**Comment by ArcerionDev** [comment]
make sure it has the proper perms to send messages

**Comment by NX721** [comment]
?

**Comment by NX721** [comment]
Ok

**Comment by NX721** [comment]
Dosen't do anything...
